export const ActionTypes = {
  STORE_ALL_PRODUCT: "STORE_ALL_PRODUCT",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  LOADER: "LOADER",
  ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",
  STORE_SESSION: "STORE_SESSION",
  STORE_ALL_CATEGORY: "STORE_ALL_CATEGORY",
  STORE_PRODUCT_BY_CATEGORY: "STORE_PRODUCT_BY_CATEGORY",
  ADD_NEW_NOTIFICATION: "ADD_NEW_NOTIFICATION",
  GET_CART_INFO: "GET_CART_INFO",
  STORE_ORDER_LIST: "STORE_ORDER_LIST",
  STORE_USER_ORDER_LIST: "STORE_USER_ORDER_LIST",
  STORE_ALL_USER_LIST: "STORE_ALL_USER_LIST",
};
//product action constant
